const KEY='rex_customers';let data=JSON.parse(localStorage.getItem(KEY)||'[]');
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(n)||0);
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function show(id){['home','customer','admin'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden');if(id==='admin')render();scrollTo(0,0)}
function resetForm(){$('form').reset();$('fstart').value=new Date().toISOString().slice(0,10)}
$('form').onsubmit=e=>{e.preventDefault();let code=$('fcode').value.trim().toUpperCase(),old=data.find(x=>x.code===code);let c={code,name:$('fname').value.trim(),phone:$('fphone').value.trim(),product:$('fproduct').value.trim(),total:+$('ftotal').value,install:+$('finstall').value||0,freq:$('freq').value,start:$('fstart').value,image:$('fimage').value.trim(),account:$('faccount').value.trim(),notes:$('fnotes').value.trim(),paid:old?.paid||0};let i=data.findIndex(x=>x.code===code);i>=0?data[i]=c:data.push(c);save();render();alert('Customer saved.');resetForm()};
function addPayment(code){let c=data.find(x=>x.code===code),bal=c.total-c.paid,n=prompt('Amount received from '+c.name+'\nCurrent balance: '+money(bal));if(n===null)return;n=+n;if(!n||n<0)return alert('Enter a valid amount.');c.paid=Math.min(c.total,c.paid+n);save();render();alert('Payment recorded. New balance: '+money(c.total-c.paid))}
function edit(code){let c=data.find(x=>x.code===code);['code','name','phone','product','total','install','freq','start','image','account','notes'].forEach(k=>{let id='f'+k;if($(id))$(id).value=c[k]??''});show('admin')}
function del(code){if(confirm('Delete this customer?')){data=data.filter(x=>x.code!==code);save();render()}}
function render(){let paid=data.reduce((a,c)=>a+c.paid,0),out=data.reduce((a,c)=>a+Math.max(0,c.total-c.paid),0);$('count').textContent=data.length;$('collected').textContent=money(paid);$('outstanding').textContent=money(out);$('list').innerHTML=data.length?data.map(c=>`<div class="row"><div><b>${esc(c.name)}</b><br><small>${esc(c.code)} • ${esc(c.product)} • Balance ${money(c.total-c.paid)}</small></div><div><button onclick="addPayment('${c.code}')">Add payment</button> <button onclick="edit('${c.code}')">Edit</button> <button onclick="del('${c.code}')">Delete</button></div></div>`).join(''):'<p>No customers yet.</p>'}
function lookup(){let code=$('code').value.trim().toUpperCase(),c=data.find(x=>x.code===code);if(!c)return $('result').innerHTML='<div class="card"><b>Customer not found.</b><p>Please check the code sent by REX SMART HUB.</p></div>';let bal=Math.max(0,c.total-c.paid),pct=c.total?Math.round(c.paid/c.total*100):0;$('result').innerHTML=`<div class="card">${c.image?`<img src="${esc(c.image)}" style="width:100%;max-height:260px;object-fit:cover;border-radius:10px">`:''}<p>REX SMART HUB</p><h2>${esc(c.product)}</h2><p>Customer: <b>${esc(c.name)}</b></p><div class="balance"><div class="money"><small>Total</small><b>${money(c.total)}</b></div><div class="money"><small>Paid</small><b>${money(c.paid)}</b></div><div class="money"><small>Remaining</small><b>${money(bal)}</b></div></div><div class="progress"><div style="width:${pct}%"></div></div><b>${pct}% paid</b> ${bal===0?'— ✅ FULLY PAID':'— Balance outstanding'}<p><b>Installment:</b> ${money(c.install)} ${esc(c.freq)}</p>${c.account?`<div class="account"><b>PAYMENT ACCOUNT</b><br><br>${esc(c.account)}</div>`:''}${c.notes?`<p>${esc(c.notes)}</p>`:''}</div>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
resetForm();render();